server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssmp?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: W2kindred

  devtools:
    restart:
      # 设置不参与热部署的文件夹或文件
      exclude: static/**,public/**,config/application.yml
      # 在启动类添加系统属性，防止其他更高级别配置文件修改热部署开关
#      enabled: false

#mybatis-plus:
#  configuration:
#    # MP日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      table-prefix: tb_
#      # id为数据库自增策略
#      id-type: auto


