spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: W2kindred
      driver-class-name: com.mysql.cj.jdbc.Driver





# 自定义memcached属性
memcached:
  servers: localhost:11211
  poolSize: 10
  opTimeout: 3000




  # 指定使用 ehcacahe
#  cache:
#    type: ehcache









  # 指定使用 Redis
#  cache:
#    type: redis
#    redis:
#      use-key-prefix: true
#      key-prefix:
      # 有效时长
#      time-to-live: 10s
#
#  redis:
#    host: XXX.XXX.XXX.XXX
#    port: 6379
#    password: myredispwd












mybatis-plus:
  configuration:
    # MP\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # id\u4E3A\u6570\u636E\u5E93\u81EA\u589E\u7B56\u7565
      id-type: auto


server:
  port: 8888
