spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: W2kindred
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto


# jetcacahe\u914D\u7F6E
jetcache:
  # \u6BCF\u8FC7\u4E00\u5206\u949F\u5411\u63A7\u5236\u53F0\u8F93\u51FA\u4E00\u6B21\u7EDF\u8BA1\u6570\u636E
  statIntervalMinutes: 1
  local:
    default:
      type: linkedhashmap
      # \u5FC5\u914D\u9879 key\u8F6C\u6362\u5668
      keyConvertor: fastjson


  remote:
    default:
      type: redis
      host: xxx.xxx.xxx.xxx
      port: 6379
      password: myredispwd
      keyConvertor: fastjson
      valueEncode: java
      valueDecode: java
      poolConfig:
        maxTotal: 50
#
#    sms:
#      type: redis
#      host: xxx.xxx.xxx.xxx
#      port: 6379
#      password: myredispwd
#      poolConfig:
#        maxTotal: 50
