spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: W2kindred
    driver-class-name: com.mysql.cj.jdbc.Driver
  # \u4F4E\u7EA7ES\u53EF\u4EE5\u914D\u7F6E
  elasticsearch:
    uris: http://localhost:9200

mybatis-plus:
  configuration:
    # MP\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # id\u4E3A\u6570\u636E\u5E93\u81EA\u589E\u7B56\u7565
      id-type: auto


