server:
  port: 8083

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssmp?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: W2kindred
  boot:
    admin:
      client:
        url: http://localhost:8082

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    # 开启所有端点
    # enabled-by-default: true

    # 端点功能暴露
    web:
      exposure:
        # 开启允许查询所有监控项
        include: "*"


mybatis-plus:
  configuration:
    # MP日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
      # id为数据库自增策略
      id-type: auto


my-appInfo:
  artifact: @project.artifactId@

# 自定义starter的配置
tools:
  ip:
    count-flush: false
    model: "detail"
    cycle: 2

